[package]
name = "offline-player-platform-macos"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
objc2-core-audio = { version = "0.3.2", default-features = false, features = [
    "AudioHardware",
    "objc2-core-audio-types",
] }

objc2-core-audio-types = { version = "0.3.2", default-features = false, features = [
    "CoreAudioBaseTypes",
    "objc2",
] }

thiserror = "2"

offline-player-audio-core = { path = "../audio-core" }
offline-player-decoder = { path = "../decoder" }